<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>..\src\DownKyi.Desktop\Resources\favicon.ico</ApplicationIcon>
        <TieredCompilation>true</TieredCompilation>
        <TieredPGO>true</TieredPGO>
        <TC_QuickJitForLoops>true</TC_QuickJitForLoops>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\src\DownKyi.Desktop\DownKyi.Desktop.csproj" />
    </ItemGroup>
</Project>
